/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    // Monsterクラスを呼び出す
    Monster myMonster = new Monster("スライム", 0);

    // ちゃんと作れたか画面に出力して確認する
    System.out.println(myMonster.toString());
    
    myMonster.summonMonster(4);
    System.out.println(myMonster.toString());
  }

}
