/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.LinkedList;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    // Monsterクラスを呼び出す
    Monster myMonster = new Monster("スライム", 0);

    // ちゃんと作れたか画面に出力して確認する
    System.out.println(myMonster.toString());

    myMonster.summonMonster(4);
    System.out.println(myMonster.toString());

    // Playerクラスで使用する固定値をLinkedListに格納
    // Randomは使用しない
    LinkedList<Integer> monsterNumbers = new LinkedList<>();

    monsterNumbers.add(0);
    monsterNumbers.add(4);
    monsterNumbers.add(0);
    monsterNumbers.add(3);
    monsterNumbers.add(1);

    // Playerクラスの動作確認
    Player player = new Player("user", monsterNumbers);

    System.out.println(player.toString());
  }

}
